name: Code::Stats Profile Cards
author: domai-tb
description: An infographics generator to display stats about your Code::Stats account!

runs:
  using: 'node20'
  main: 'action.ts'

inputs:
  username:
    description: Code::Sats account username
    required: true
    default: domai-tb
