name: Code::Stats Profile Cards
author: domai-tb
description: An infographics generator to display stats about your Code::Stats account!

runs:
  using: 'node20'
  main: 'dist/action.js'

inputs:
  username:
    description: Code::Sats account username
    required: true
    type: string
    default: domai-tb

  show_icons:
    description: Generate profile card with icons
    required: false
    type: boolean
    default: true

  hide_rank:
    description: Generate profile card without level / rank
    required: false
    type: boolean
    default: false

  hide_title:
    description: Generate cards without title
    required: false
    type: boolean
    default: false

  hide_border:
    description: Generate cards without border
    required: false
    type: boolean
    default: false

  line_height:
    description: Line hight for profile card
    required: false
    type: number
    default: 45

  title_color:
    description: Color of profile card title
    required: false
    type: string

  icon_color:
    description: Color of profile card icons
    required: false
    type: string

  text_color:
    description: Color of profile card text
    required: false
    type: string

  bg_color:
    description: Color of top language card background
    required: false
    type: string

  language_count:
    description: Number of language to display on cards
    required: false
    type: number
    default: 21

  hide:
    description: Hide specific language from top lang card
    required: false
    type: string
    default: 'scminput,Log,Plain text'

  card_width:
    description: Width of top languages card in px
    required: false
    type: number
    default: 300

  card_height:
    description: Higths of top languages card in px
    required: false
    type: number
    default: 300

  layout:
    description: Layout of top lang card
    required: false
    type: choice
    options: 
      - compact
      - undefiend
    default: compact

  hide_legend:
    description: Generate history card without legend
    required: false
    type: boolean
    default: false

  reverse_order:
    description: Order history from old to new
    required: false
    type: boolean
    default: false